services:
  postgres_mastra:
    image: ankane/pgvector:latest
    container_name: mastra_postgres
    environment:
      POSTGRES_USER: mastra
      POSTGRES_PASSWORD: zeus
      POSTGRES_DB: mastra
    ports:
      - "4444:5432"
    volumes:
      - postgres_mastra_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  postgres_mastra_data: {}